# Generated by Django 4.1 on 2023-07-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='phone_no',
            field=models.IntegerField(max_length=10),
        ),
    ]
