# Generated by Django 4.1 on 2023-07-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_students_phone_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name_plural': 'Students'},
        ),
        migrations.AlterField(
            model_name='students',
            name='phone_no',
            field=models.IntegerField(),
        ),
    ]
