# Generated by Django 4.1 on 2023-07-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_students_options_alter_students_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='UplaodedExcel')),
            ],
        ),
    ]
